### ISSUE TITLE
v2.16.08 login issue

### ISSUE THREAD

**Issue by cfcnightmare** [mkschreder/mks-openwrt-feed#11]
Orangectl isnt working...
![virtualbox_opev_27_08_2016_15_58_00](https://cloud.githubusercontent.com/assets/9579109/18027539/5030bbdc-6c6f-11e6-9e13-364056289245.png)

**Comment by mkschreder** [comment]
Something is wrong with your build process and also you are trying to call
the server executable with an invalid parameter (stop). I think you meant
to write "/etc/init.d/orange stop".

Are you sure that you are building from v2.16.08 of the juci feed? The
orangectl script is not present in master yet.

**Comment by cfcnightmare** [comment]
im sure, its 2.16.08 (today build)
![virtualbox_ubuntu16_27_08_2016_16_53_52](https://cloud.githubusercontent.com/assets/9579109/18027848/e021100a-6c76-11e6-8487-b819924c607c.png)
did you try to build it by yourself?

UPD orangectl is a bash script, thats why its not executed. Default cmd line interpreter is ash....

**Comment by cfcnightmare** [comment]
can you make a version, which will compile and working?
I mean v2...
Or update compiling instructions please...
I build everytime you change something! And no profit. 
What reason of updating packages if it dont working together?
Just try to compile v2.16.08  openwrt-feed and look!
