### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cfcnightmare** [mkschreder/mks-openwrt-feed#13]
make[3]: Leaving directory '/home/openwrt/openwrt/package/utils/lua'
make[3]: Entering directory '/home/openwrt/openwrt/package/libs/libubox'
mkdir -p /home/openwrt/openwrt/dl
echo "Checking out files from the git repository..."; mkdir -p /home/openwrt/openwrt/tmp/dl && cd /home/openwrt/openwrt/tmp/dl && rm -rf libubox-2015-11-08 && [ ! -d libubox-2015-11-08 ] && git clone http://git.openwrt.org/project/libubox.git libubox-2015-11-08 --recursive && (cd libubox-2015-11-08 && git checkout 10429bccd0dc5d204635e110a7a8fae7b80d16cb && git submodule update) && echo "Packing checkout..." && rm -rf libubox-2015-11-08/.git &&    tar czf /home/openwrt/openwrt/tmp/dl/libubox-2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb.tar.gz libubox-2015-11-08 && mv /home/openwrt/openwrt/tmp/dl/libubox-2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb.tar.gz /home/openwrt/openwrt/dl/ && rm -rf libubox-2015-11-08;
Checking out files from the git repository...
Cloning into 'libubox-2015-11-08'...
fatal: unable to access 'http://git.openwrt.org/project/libubox.git/': Failed to connect to git.openwrt.org port 80: Connection timed out
Makefile:95: recipe for target '/home/openwrt/openwrt/dl/libubox-2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb.tar.gz' failed
make[3]: **\* [/home/openwrt/openwrt/dl/libubox-2015-11-08-10429bccd0dc5d204635e110a7a8fae7b80d16cb.tar.gz] Error 128
make[3]: Leaving directory '/home/openwrt/openwrt/package/libs/libubox'
package/Makefile:191: recipe for target 'package/libs/libubox/compile' failed
make[2]: **\* [package/libs/libubox/compile] Error 2
make[2]: Leaving directory '/home/openwrt/openwrt'
package/Makefile:188: recipe for target '/home/openwrt/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: **\* [/home/openwrt/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt'
/home/openwrt/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: **\* [world] Error 2
openwrt@ubuntu:~/openwrt$

Something wrong with openwrt git...

**Comment by mkschreder** [comment]
Looks like openwrt git server was down when you were building.
