### ISSUE TITLE
orangerpcd build failed

### ISSUE THREAD

**Issue by cfcnightmare** [mkschreder/mks-openwrt-feed#14]
/home/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/x86_64-openwrt-linux-uclibc/4.8.3/../../../../x86_64-openwrt-linux-uclibc/bin/ld: cannot find -lssp_nonshared
/home/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/x86_64-openwrt-linux-uclibc/4.8.3/../../../../x86_64-openwrt-linux-uclibc/bin/ld: cannot find -lssp
/home/openwrt/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/usr/lib/libuci.so: warning: the use of `mktemp' is dangerous, better use`mkstemp'
collect2: error: ld returned 1 exit status
Makefile:484: recipe for target 'orangerpcd' failed
make[5]: **\* [orangerpcd] Error 1
make[5]: Leaving directory '/home/openwrt/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/orange-rpcd-2.16.08-c4ad159efa5fc40f610fa0cb11e25fda19f131ad/src'
Makefile:391: recipe for target 'all-recursive' failed
make[4]: **\* [all-recursive] Error 1
make[4]: Leaving directory '/home/openwrt/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/orange-rpcd-2.16.08-c4ad159efa5fc40f610fa0cb11e25fda19f131ad'
Makefile:65: recipe for target '/home/openwrt/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/orange-rpcd-2.16.08-c4ad159efa5fc40f610fa0cb11e25fda19f131ad/.built' failed
make[3]: **\* [/home/openwrt/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/orange-rpcd-2.16.08-c4ad159efa5fc40f610fa0cb11e25fda19f131ad/.built] Error 2
make[3]: Leaving directory '/home/openwrt/openwrt/feeds/juci/orange-rpcd'
package/Makefile:191: recipe for target 'package/feeds/juci/orange-rpcd/compile' failed
make[2]: **\* [package/feeds/juci/orange-rpcd/compile] Error 2
make[2]: Leaving directory '/home/openwrt/openwrt'
package/Makefile:188: recipe for target '/home/openwrt/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile' failed
make[1]: **\* [/home/openwrt/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt'
/home/openwrt/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: **\* [world] Error 2
openwrt@ubuntu:~/openwrt$

with your script or without same issue...

**Comment by cfcnightmare** [comment]
![default](https://cloud.githubusercontent.com/assets/9579109/18286641/694639c0-747c-11e6-923a-083922d01fe4.jpg)
make[4]: Entering directory '/home/openwrt/openwrt/build_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/uClibc-0.9.33.2'
make[4]: Circular libpthread/nptl/sysdeps/x86_64/gen_tcb-offsets.s <- libpthread/nptl/sysdeps/x86_64/tcb-offsets.h dependency dropped.
rm -f lib/libc.so lib/libc.so.0 lib/libuClibc-0.9.33.2.so
x86_64-openwrt-linux-uclibc-gcc -Wl,-EL -shared -Wl,--warn-common -Wl,--warn-once -Wl,-z,combreloc -Wl,-z,relro -Wl,-z,defs   -Wl,-init,__uClibc_init  -Wl,-soname=libc.so.0 -nostdlib -o lib/libuClibc-0.9.33.2.so  -Wl,--whole-archive libc/libc_so.a -Wl,--no-whole-archive ./lib/interp.os ./lib/ld64-uClibc.so.0 ./lib/uclibc_nonshared.a /home/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/x86_64-openwrt-linux-uclibc/4.8.3/libgcc_initial.a
libc/libc_so.a(wordexp.os): In function `exec_comm':
/home/openwrt/openwrt/build_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/uClibc-0.9.33.2/libc/misc/wordexp/wordexp.c:798: undefined reference to`__stack_chk_guard'
collect2: error: ld returned 1 exit status
libc/Makefile.in:64: recipe for target 'lib/libc.so' failed
make[4]: **\* [lib/libc.so] Error 1
make[4]: Leaving directory '/home/openwrt/openwrt/build_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/uClibc-0.9.33.2'
Makefile:41: recipe for target '/home/openwrt/openwrt/build_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/uClibc-0.9.33.2/.built' failed
make[3]: **\* [/home/openwrt/openwrt/build_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/uClibc-0.9.33.2/.built] Error 2
make[3]: Leaving directory '/home/openwrt/openwrt/toolchain/uClibc'
toolchain/Makefile:81: recipe for target 'toolchain/uClibc/compile' failed
make[2]: **\* [toolchain/uClibc/compile] Error 2
make[2]: Leaving directory '/home/openwrt/openwrt'
toolchain/Makefile:80: recipe for target '/home/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/stamp/.toolchain_install' failed
make[1]: **\* [/home/openwrt/openwrt/staging_dir/toolchain-x86_64_gcc-4.8-linaro_uClibc-0.9.33.2/stamp/.toolchain_install] Error 2
make[1]: Leaving directory '/home/openwrt/openwrt'
/home/openwrt/openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: **\* [world] Error 2

**Comment by mkschreder** [comment]
I think it is probably -fstack-protect-all flag in the makefile that I have added recently. It is strange that it does not compile for you because for me it builds fine even though I have SSP_SUPPORT disabled in the config.. Anyways, I have removed that flag for now and pushed latest feed update.
