### ISSUE TITLE
rpc connection failed!

### ISSUE THREAD

**Issue by cfcnightmare** [mkschreder/mks-openwrt-feed#15]
![default](https://cloud.githubusercontent.com/assets/9579109/18291971/89dc3c36-7493-11e6-9dda-f212b455d1f3.png)

**Comment by mkschreder** [comment]
Try completely removing lighttpd package that comes with openwrt.

**Comment by cfcnightmare** [comment]
did like you said:
./scripts/feeds update -a 
./scripts/feeds install -f -a -p juci
./scripts/feeds install -a
./scripts/feeds uninstall lighttpd
./scripts/feeds install -f -a -p juci
lighttpd installed

![default](https://cloud.githubusercontent.com/assets/9579109/18322008/382a3b3a-7539-11e6-8aa9-981db8c6f1ca.png)
error changed from 404 to 503 :)

**Comment by mkschreder** [comment]
At least you are getting 503 instead of 404 now. So now check that
orangerpcd is installed and running.

**Comment by cfcnightmare** [comment]
Made orangerpcd command and it starts?)))

![default](https://cloud.githubusercontent.com/assets/9579109/18325734/51c912de-754b-11e6-8b55-7f52d2b0cf5d.png)

also see messages :sh ip not found
May be its ip package of busybox? ( i did not selected it)

And in main screen its black background now (network map), can you return old background? (blue) :)
![default](https://cloud.githubusercontent.com/assets/9579109/18325930/36e5562a-754c-11e6-9a7f-2e1c6410e0fb.png)

commit that version pls!

PS add commands i made to a main FAQ (uninstall lighttpd)
Thats great work Martin!!! Thank you!

**Comment by mkschreder** [comment]
So you got it working? :-)

**Comment by mkschreder** [comment]
There are a few menu pages that are missing but I'll update the default
files soon... You should fork them anyway for custom builds.

**Comment by cfcnightmare** [comment]
I didnt check yet...
Tomorrow i will recompile with drivers (atk10k,ath9k) ,zram and ip package in busybox and check

**Comment by cfcnightmare** [comment]
Also its interesting to make easy vpn connecting ( like in ipfire)
Also for me lcd4linux package is interesting but it missed in 15.05...

**Comment by mkschreder** [comment]
What board are you building for?

**Comment by cfcnightmare** [comment]
Socket AM1 (athlon 5350 2gHzx4 )
2gb ddr3 ram
Network intel pro 1000 ( dual port)
Wireless Mikrotik r11e-5HacT (1.3gbit/s) AC
                Mikrotik r11e-2HPnD (300 mbit/s) bgn
Wifi cards installed in Mikrotik rb14eu

Want to deploy display which will show speeds, processor/ram utilization and other...
Tested on openwrt trunk ( works)
Also ipfire ( works)
Used Samsung SPF-75 :)
![img_20160228_015035_hdr](https://cloud.githubusercontent.com/assets/9579109/18326812/51cde0e8-7550-11e6-9373-4bdba83468c9.jpg)
