### ISSUE TITLE
[v1.15.12]:Login Error

### ISSUE THREAD

**Issue by lvzaina** [mkschreder/mks-openwrt-feed#2]
When I update the new version (v1.15.11 => v1.15.12), can not pass the user name password, view the console log:

```
UCI failed to initialize!
```

**Comment by mkschreder** [comment]
I have had an occasional problem with rpcd crashing upon empty uci values
last week. It could be the same problem for you as well. I pinpointed the
crash and fixed it in the rpcd that juci uses. It could be something else
too. Try starting rpcd manually and see if it ends up crashing at some
point.
