### ISSUE TITLE
uncaught exception: TypeError: $rpc.juci.network is undefined 

### ISSUE THREAD

**Issue by gaurawgiri** [mkschreder/mks-openwrt-feed#28]
Installed JUCI with owrt but when we access the web pages , one pop-up
observed with error "uncaught exception: TypeError: $rpc.juci.network is undefined "

Below is the error in console.
```
UCI failed to initialize!  01-juci.js:1:1794944
JUCIMain.prototype.$init/</< http://192.168.168.1/js/01-juci.js:1:1794944
n.Callbacks/j http://192.168.168.1/js/01-juci.js:1:909346
n.Callbacks/k.fireWith http://192.168.168.1/js/01-juci.js:1:910164
.Deferred/</e[f[0]] http://192.168.168.1/js/01-juci.js:1:911130
UCI.prototype.$init/< http://192.168.168.1/js/01-juci.js:1:1788766
n.Callbacks/j http://192.168.168.1/js/01-juci.js:1:909346
n.Callbacks/k.fireWith http://192.168.168.1/js/01-juci.js:1:910164
.Deferred/</e[f[0]] http://192.168.168.1/js/01-juci.js:1:911130
RevoRPC.prototype.$connect/socket.onmessage http://192.168.168.1/js/01-juci.js:1:1764257
window.onerror http://192.168.168.1/js/01-juci.js:1:1800530
$juci.redirect http://192.168.168.1/js/01-juci.js:1:1799578
$juci.redirectHome/< http://192.168.168.1/js/01-juci.js:1:1801358
JUCI Init
```

Is this something related to *client side javascript* or *lua* ?  Also the following are succeeded as per console logs

>RPC init  01-juci.js:1:1794425
connecting to rpc server at (ws://192.168.168.1/websocket/)  01-juci.js:1:1763223
RPC connection established!  01-juci.js:1:1763305
RPC initialized!  01-juci.js:1:1794635
UCI Init

**Comment by mkschreder** [comment]
You get this error when the RPC is not working properly. Javascript rpc objects are automatically mapped to backend API which in turn maps some objects to ubus. The objects on ubus too depend on the services which provide them such as for example netifd. You can fire up orange-rpcd with =-vvv= flag to print out a lot of debug info that can help you debug this.
