### ISSUE TITLE
With what version?

### ISSUE THREAD

**Issue by darcyg** [mkschreder/mks-openwrt-feed#7]
With 2.16.05 or 2.16.03?

How to use it?

Test 2.16.05
Close luci/uhttpd service
Configure lighttpd, port 100, directory /www
Run juci-update.
Run lighttpd
No /sbin/juci
There are juci-netdevd and juci-eventd
Browser open http://192.168.1.1:100
No user interface

**Comment by cfcnightmare** [comment]
I can't compile v2 too. By the way v1.15.12 is compiled with 15.05.1 Openwrt (not fully working)

**Comment by mkschreder** [comment]
16.02 is stable for now. 16.05 is experimental.
