### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by cfcnightmare** [mkschreder/mks-openwrt-feed#8]
Martin hello again :)
Can you say, Juci is compatible with Atheros wifi cards ?
I was reading somewhere that you working with Broadcom only. 
I know that Juci is only GUI but will it collaborate with Hostapd and ath10k?
Anyway i cant compile 15.05 with v2.16.XX  because of  luaposix compile error ....
Any advance?

**Comment by mkschreder** [comment]
There is no specific broadcom dependency anymore.

Luaposix problem has been there for some users for a while. Although I have
not experienced it myself. I will have to look into it when I have time.

**Comment by cfcnightmare** [comment]
CLOSED!
